- name: "Create install script temp file path"
  set_fact:
    docker_install_script_path: '/tmp/docker_install_script.sh'

- name: "Download docker official install script"
  get_url:
    dest: '{{ docker_install_script_path }}'
    force: true
    url: https://get.docker.com
    validate_certs: true

- name: "Run the script"
  command: '/bin/sh {{ docker_install_script_path }}'

- name: "Delete downloaded file"
  file:
    path: '{{ docker_install_script_path }}'
    state: absent
