---
- name: "Check whether docker exists"
  shell: command -v docker
  ignore_errors: True
  register: docker_exists
  changed_when: false
  check_mode: false

- name: "Install GPG Dependency"
  apt:
    name: gnupg2
    state: latest

- name: Install Python Dependency
  apt:
    name: python3-apt
    state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update apt cache and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: "Ensure 'docker' group present"
  group:
    name: docker
    state: present
    system: true

- name: "Add users into 'docker'"
  user:
    append: true
    groups: docker
    state: present
    name: ubuntu

- name: "Enable docker service"
  service:
    name: docker
    enabled: true

- name: "Start docker"
  service:
    name: docker
    state: started
